language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Support library
    - extra-android-support

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-26
    - sys-img-armeabi-v7a-android-17
before_install:
 - chmod +x gradlew
 deploy:
  provider: releases
  api_key: 7888a5134a5a92012e69fdda0ff6dfe6b8be1a53
  file: /home/travis/build/mobile--android/app/build/outputs/apk/*
  skip_cleanup: true
  on:
    repo : romanvit13/mobile--android
    tags: false
    all_branches: true
script:
- chmod +x ./gradlew
- ./gradlew clean assembleDebug test lint
