language: android
sudo: required
before_cache:
 -rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 -rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
 directories:
 -$HOME/.gradle/caches/
 -$HOME/.gradle/wrapper/
 env:
 global:
 - ANDROID_API=28
 - EMULATOR_API=26
 - ANDROID_BUILD_TOOLS=28.0.3
 - ADB_INSTALL_TIMEOUT=5 # minutes
 - storepass=123456
 - keypass=123456
android:
  components:
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    # Support library
    - extra-android-support
    # Emulators
    - sys-img-x86-android-$EMULATOR_API
    - sys-img-armeabi-v7a-android-17
    
before_deploy:
- cp $TRAVIS_BUILD_DIR/.keystore $HOME
- cd app/build/outputs/apk/
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/keystore.jks -storepass $storepass -keypass $keypass app-release-unsigned.apk yourapp_keystore
# Verification
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/24.0.2/zipalign -v 4 app-release-unsigned.apk yourapp.apk"

deploy:
  provider: releases
  file: CatsApp.apk
  skip_cleanup: true
  on:
    repo: romanvit13/mobile--android
    tags: true
    jdk: oraclejdk8
  api_key:
    secure: keystore.jks
    
before_install:
 - chmod +x gradlew
script:
- chmod +x ./gradlew
- ./gradlew clean assembleDebug test lint
